{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "horilla-ph.postgresql.fullname" . }}
  labels:
    {{- include "horilla-ph.labels" . | nindent 4 }}
type: Opaque
data:
  postgresql-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
{{- end }}
