apiVersion: v1
kind: Secret
metadata:
  name: {{ include "horilla-ph.fullname" . }}
  labels:
    {{- include "horilla-ph.labels" . | nindent 4 }}
type: Opaque
data:
  # base64-encoded at render time by Helm
  SECRET_KEY: {{ .Values.appSecrets.secretKey | b64enc | quote }}
  {{- if .Values.postgresql.enabled }}
  DB_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
  {{- else if not .Values.externalDatabase.existingSecret }}
  DB_PASSWORD: {{ "" | b64enc | quote }}
  {{- end }}
